#!/bin/bash
#Request 16 gigabytes of virtual (mem) and 4Gig real (rmem) memory
#$ -l mem=16G -l rmem=4G
#Run 10 tasks where each task has a different $SGE_TASK_ID ranging from 1 to 10
#$ -t 1-10

#Output the Task ID
echo "Task ID is $SGE_TASK_ID"

#Load the MATLAB 2016a Environment modulue
module load apps/matlab/2016a

#Run the function, passing $SGE_TASK_ID to it 
matlab -nodisplay -r "myfunc $SGE_TASK_ID"
